//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LNTKKiosk.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStock
    {
        public int OrderId { get; set; }
        public int StockId { get; set; }
        public string Dummy { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
