//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LNTKKiosk.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock()
        {
            this.OrderStocks = new HashSet<OrderStock>();
        }
    
        public int StockId { get; set; }
        public int GroceryId { get; set; }
        public System.DateTime ReceivedDate { get; set; }
        public Nullable<int> ExpirationDate { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<System.DateTime> ExhaustedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderStock> OrderStocks { get; set; }
        public virtual Grocery Grocery { get; set; }
    }
}
